#!/bin/bash
cecho() {
  local code="\033["
  case "$1" in
    red    |  r) color="${code}1;31m";;
    green  |  g) color="${code}1;32m";;
    yellow |  y) color="${code}1;33m";;
    blue   |  b) color="${code}1;34m";;
    purple |  p) color="${code}1;35m";;
    cyan   |  c) color="${code}1;36m";;
    gray   | gr) color="${code}0;37m";;
    *) local text="$1"
  esac
  [ -z "$text" ] && local text="$color$2${code}0m"
  echo -n -e "$text"
}

checkstatus () {
  check=$($chain dicestatus $fundname $fundingtxid $sendbet | jq -r '.')
  result=$(jq -r ".status" <<<"${check}")
}

waitforconfirm () {
  confirmations=0
  while [[ ${confirmations} -lt 1 ]]; do
    sleep 1
    confirmations=$($chain getrawtransaction $1 1 | jq -r .confirmations)
    if [[ $confirmations = "" ]]; then
      echo "$1" >> failed_bet_transactions
      echo "$bethex" >> failed_bet_transactions
      failed_round=1
      return
    fi
    failed_round=0
    $chain sendrawtransaction $($chain getrawtransaction $1) > /dev/null 2>&1
done
}

bet () {
  bet=$($chain dicebet $fundname $fundingtxid $wager $odds | jq -r '.')

  if [[ $(echo $bet | jq -r .result) = error ]]; then
  	cecho r "$(echo $bet | jq -r .error)\n"
  	exit
  fi
  bethex=$(jq -r ".hex" <<<"${bet}")

  sendbet=$($chain sendrawtransaction $bethex)
  outcome=$?
  if [[ $outcome != 0 ]]; then
  	cecho r "SEND: $sendbet FAILED!\n"
  	exit
  fi
  cecho b "Sent: "
  cecho c "$sendbet\n"
  sent=$(date +%s)
  echo "SENT: $sendbet at $sent">> txids_sent
  checkstatus
  outcome=0
  while [[ $outcome = 0 ]]; do
    if [[ $result = *pending* ]]; then
      sleep 10
      checkstatus
    else
      outcome=1
    fi
  done

  if [[ $result = "win" ]]; then
    cecho g "YOU WON!"
    echo $sendbet >> wins
  elif [[ $result = "loss" ]]; then
    cecho r "YOU LOST!"
    echo $sendbet >> losses
  else
    cecho c "result: $result"
  fi
  echo ""
}

source ac
fundingtxid="bece4eada17c8f9273f609ebf93aefe4d224d97df2a45a0ecacabd7df9e6c5fb"
fundname="LOW"
chain="komodo-cli -ac_name=$ac"

if [ -z ${1+x} ] || [ -z ${2+x} ] || [ -z ${3+x} ]; then
  echo ""
  cecho r "You need to specify wager, odds and times to play!\n"
  cecho g "eg. ./dice 1 1 1\n"
  echo ""
  exit
fi

wager=$1
cecho b "Wager: "
cecho g "$wager\n"
odds=$2
cecho b "Odds: "
cecho g "$odds\n"
failed_round=0

for i in `seq 1 $3`; do
  bet
  waitforconfirm $sendbet
  if [[ $failed_round = 0 ]]; then
    confirmtime=$(( $(date +%s) -$sent ))
    cecho g "Bet transaction confirmed in: $confirmtime seconds \n"
    echo "$sendbet confirmed in: $confirmtime" >> txids_confirmed
  fi
  sleep $(( RANDOM % 60 ))
done
